# Base image for Docker to build layers on top of
# Use Python 3.10 as the base image



# Install additional troubleshooting tools for the image for future debugging
# tet-tools for ifconfig, netstat, etc.
# iputils-ping for the ping command



# Copy requirements.txt file to image to install Python dependencies, before
# copying the rest of the application code



# Install the required Python packages from the requirements.txt file



# COPY the website directory to the image that contains the Flask app
# and pages and picture



# Describe to the user that the application uses port 8000 internally to listen on for connections for the web server 



# Set the working directory to the website directory, where future commands will be run from



# Set the base command to run the Flask app using gunicorn when the container starts


